# Generated by Django 5.0.6 on 2024-05-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("SETBX_ID", models.IntegerField(primary_key=True, serialize=False)),
                ("USER_EMAIL", models.CharField(max_length=100)),
                ("USER_PWD", models.CharField(max_length=100)),
                ("USER_NAME", models.CharField(max_length=50)),
                ("USER_PHONE", models.CharField(max_length=50)),
                ("user_sex", models.CharField(max_length=10)),
                ("USER_BIRTH", models.DateField()),
                ("USER_ADULT", models.CharField(max_length=10)),
                ("USER_ADULT_KEY", models.CharField(max_length=20)),
                ("USER_LIKE_GENRE", models.CharField(max_length=100)),
                ("USER_LIKE_VOD", models.CharField(max_length=100)),
            ],
        ),
    ]
