# Generated by Django 5.0.6 on 2024-05-25 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cud_userapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Signup",
        ),
    ]
